### PR TITLE
chore: bump github.com/goccy/go-json to v0.10.4

### PR DESCRIPTION
**Pull request by toddtreece**
### Rationale for this change

A follow up to https://github.com/apache/arrow-go/pull/199#issuecomment-2494887343

> i will continue trying to get the go-json PR merged, and if i do, i'll open another PR to update the dependency here.

### What changes are included in this PR?

Bumps go-json dependency to include changes from https://github.com/goccy/go-json/pull/490

### Are these changes tested?

I am assuming CI tests should cover this.

### Are there any user-facing changes?

No

### CODE REVIEW

**Comment by zeroshade** [comment]
Would it be possible to get goccy to do a release of `go-json` rather than us pointing to a specific commit?

**Comment by toddtreece** [comment]
@zeroshade i will try via gophers slack, but it might also help if you could comment on the `go-json` PR asking for a release since this is a direct dependency of `arrow-go`

**Comment by toddtreece** [comment]
@zeroshade `v0.10.4` was released 🎉. i updated this PR, so it should be ready for another look

**Comment by zeroshade** [comment]
Once this merges, I think I would want to get a couple other PRs on here merged first and then I would be happy to start the release process

**Review by zeroshade — APPROVED** [review]

**Pull request merged**
